/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eje1g4_1.Vistas;

import eje1g4_1.AccesoADatos.Conexion;
import eje1g4_1.AccesoADatos.MateriaData;
import eje1g4_1.Entidades.Materia;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Michi
 */
public class GestionDeMateria extends javax.swing.JInternalFrame {
Materia mat = new Materia();
MateriaData matD = new MateriaData();

    /**
     * Creates new form Materia
     */
    public GestionDeMateria() {
      Connection  con = Conexion.getConexion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jBuscar = new javax.swing.JButton();
        jTnombre = new javax.swing.JTextField();
        jTaño = new javax.swing.JTextField();
        jRestado = new javax.swing.JRadioButton();
        jBnuevoM = new javax.swing.JButton();
        jbGuardarM = new javax.swing.JButton();
        jBeliminarM = new javax.swing.JButton();
        jBsalirM = new javax.swing.JButton();

        jButton5.setText("jButton5");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Año:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jBnuevoM.setText("Nuevo");
        jBnuevoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoMActionPerformed(evt);
            }
        });

        jbGuardarM.setText("Guardar");
        jbGuardarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarMActionPerformed(evt);
            }
        });

        jBeliminarM.setText("Eliminar");
        jBeliminarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBeliminarMMouseClicked(evt);
            }
        });
        jBeliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarMActionPerformed(evt);
            }
        });

        jBsalirM.setText("Salir");
        jBsalirM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsalirMMouseClicked(evt);
            }
        });
        jBsalirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTcodigo)
                            .addComponent(jTnombre)
                            .addComponent(jTaño)
                            .addComponent(jRestado, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(jBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jBnuevoM)
                        .addGap(18, 18, 18)
                        .addComponent(jbGuardarM)
                        .addGap(18, 18, 18)
                        .addComponent(jBeliminarM)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalirM)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRestado)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevoM)
                    .addComponent(jbGuardarM)
                    .addComponent(jBeliminarM)
                    .addComponent(jBsalirM))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirMActionPerformed
       
    }//GEN-LAST:event_jBsalirMActionPerformed

    private void jBsalirMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsalirMMouseClicked
         this.dispose();
    }//GEN-LAST:event_jBsalirMMouseClicked

    private void jBeliminarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBeliminarMMouseClicked
       
    }//GEN-LAST:event_jBeliminarMMouseClicked

    private void jBeliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarMActionPerformed
        
        matD.eliminarMateria(Integer.parseInt(jTcodigo.getText()));
        jRestado.setText("");
        jTaño.setText("");
        jTcodigo.setText("");
        jTnombre.setText("");
    }//GEN-LAST:event_jBeliminarMActionPerformed

    private void jbGuardarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarMActionPerformed
       
       
       int anio= Integer.parseInt(jTaño.getText());
       String nombre= jTnombre.getText();
       mat.getIdMateria();
       mat.setAnioMateria(anio);
       mat.setNombre(nombre); 
       matD.guardarMateria(mat);
       matD.modificarMateria(mat);
        
    }//GEN-LAST:event_jbGuardarMActionPerformed

    private void jBnuevoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoMActionPerformed
         int anio= Integer.parseInt(jTaño.getText());
       String nombre= jTnombre.getText();
       
       mat.getIdMateria();
       mat.setAnioMateria(anio);
       mat.setNombre(nombre); 
       matD.guardarMateria(mat);
       
        jRestado.setText("");
        jTaño.setText("");
        jTcodigo.setText("");
        jTnombre.setText("");  
    }//GEN-LAST:event_jBnuevoMActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        int codigo = Integer.parseInt(jTcodigo.getText());
       Materia mate= matD.buscarMateria(codigo);
        if(mate==null){
        
            JOptionPane.showMessageDialog(this,"La materia con el código ingresado no se encuentra disponible intentelo nuevamente");

        }else{
        jTaño.setText(Integer.toString(mate.getAnioMateria()));
        jTnombre.setText(mate.getNombre());
        jRestado.setEnabled(mat.isActivo());
        
        }
    }//GEN-LAST:event_jBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminarM;
    private javax.swing.JButton jBnuevoM;
    private javax.swing.JButton jBsalirM;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRestado;
    private javax.swing.JTextField jTaño;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JButton jbGuardarM;
    // End of variables declaration//GEN-END:variables
}
